

on: 
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker build -t action_docker .

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: xhuve
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: docker/build-push-action@v5
        context: ../..
        file: ../../Dockerfile
        push: true
